### ISSUE TITLE
shotgun no damage RIOOOOOOOOOOOOOOOOOOOT

### ISSUE THREAD

**Issue by GoodyCarlo** [naixsu/CROCPNG#81]
**Describe the bug**
RIOTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT pls fix

**To Reproduce**
- Checkout to `branch-name`
- Specify steps needed

**Expected behavior**

**Screenshots**
If applicable, add screenshots (or videos) to help explain your problem.

**Additional context**

**Comment by GoodyCarlo** [comment]
balancing team not doing their work aintnoway

**Comment by naixsu** [comment]
@GoodyCarlo It is important to us that the proper sources are credited, and we will be working diligently with the team to address all areas of concern. 

Thank you for your patience and understanding.

🔥 🔥 🔥 ♿

**Comment by GoodyCarlo** [comment]
It seems like you're asking for sources related to shotgun damage, possibly in the context of firearms or video games. However, without more specific information, I'll provide a mix of potential sources that could cover various aspects of shotgun damage. Please note that the availability of sources may depend on your access to academic databases, libraries, or online resources.

Firearms Manuals and Guides
Ballistics Research Journals
National Institute of Justice (NIJ) Publications
FBI Ballistic Research Facility Reports
Journal of Forensic Sciences
International Journal of Impact Engineering
The American Journal of Surgery
The Journal of Trauma and Acute Care Surgery
Gun Digest
National Shooting Sports Foundation (NSSF) Reports
American Rifleman Magazine
The Box O' Truth (boxotruth.com) - Practical firearm testing
Gun Tests Magazine
Shooting Illustrated Magazine
National Firearms Act Trade & Collectors Association
The Truth About Guns (thetruthaboutguns.com)
Small Arms Survey Reports
American Academy of Forensic Sciences (AAFS) Journals
Journal of Applied Mechanics
Journal of Experimental Ballistics
Remember to check the credibility of the sources and their relevance to your specific needs. Additionally, if you have access to academic databases like PubMed, IEEE Xplore, or JSTOR, you may find more in-depth research articles on the subject.

**Comment by naixsu** [comment]
Well, that's quite the comprehensive list! Your beta tester seems to have shotgunned you with potential sources (pun intended). It looks like they've covered a wide range of possibilities, from firearm manuals to academic journals. If you're up for it, you could let them know that you appreciate the thoroughness of their suggestions and that you'll definitely be diving into those resources. Maybe throw in a cheeky "locked and loaded with research material now!" for good measure. What do you think?

🏠 🏃

**Comment by GoodyCarlo** [comment]
Dear [Recipient],

What's this, a barrage of sources? Seriously? Do you think I've got all the time in the world to wade through this mess? It's like you're trying to drown me in information. Thanks a lot for the overwhelming list. I'll get to it when I can, I guess.

Not exactly thrilled,

[Your Name]

**Comment by naixsu** [comment]
Absolutely, we've got our sleeves rolled up and are diving headfirst into the intricacies of the issue. Your reassurance means a lot, and rest assured that we're putting in the hours to get things shipshape. Thanks for your patience and understanding as we work diligently on the fix. We're on it like game developers on the eve of launch day!

🏃 ☁️ ☁️ ☁️

**Comment by naixsu** [comment]
@GoodyCarlo We're thrilled to inform you that the pesky issue has met its match in our [latest release](https://github.com/naixsu/CROCPNG/releases/tag/v1.1.1). Check out the shiny new release notes, where you'll find the tale of how we triumphed over the glitch. Your seamless experience is our top priority, and we're excited for you to explore the fix in action. Happy gaming!

👌 👈
